<?php

return [
    // The Telegram BOT api token
    'token' => env('TELEGRAM_TOKEN'),

    // if the webhook mode must validate the incoming IP range is from a telegram server
    'safe_mode' => env('APP_ENV', 'local') === 'production',

    // Extra or specific configurations
    'config' => [
        'timeout' => 60,
        'connect_timeout' => 10,
        'api_url' => env("TELEGRAM_API_URL", "https://api.telegram.org"),
        'is_local' => true,
    ],

    // Set if the service provider should automatically load
    // handlers from /routes/telegram.php
    'routes' => true,

    // Enable or disable Nutgram mixins
    'mixins' => false,
    'is_local' => true,

    // Path to save files generated by nutgram:make command
    'namespace' => app_path('Telegram'),

    // Set log channel
    'log_channel' => 'null', // env('TELEGRAM_LOG_CHANNEL', 'null'),

    'cache_channel' => env('TELEGRAM_CACHE_CHANNEL'),

    'admins_id' => [
        "admin_id1" => env("TELEGRAM_ADMIN_ID1"),
        "admin_id2" => env("TELEGRAM_ADMIN_ID2"),
        "admin_id3" => env("TELEGRAM_ADMIN_ID3"),
        "admin_id4" => env("TELEGRAM_ADMIN_ID4"),
        "admin_id5" => env("TELEGRAM_ADMIN_ID5"),
    ],
];
